name: Automate Release

on:
  push:
    branches:
      - main
      - release/*

jobs:
  version_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      packages: write

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-deps # Identificador único para este cache
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('.releaserc') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      # Step 2.1: Configure .npmrc for GitHub Packages
      - name: Configure .npmrc for GitHub Packages
        run: |
          echo "@lordcrainer:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      # Step 4: Install semantic-release and plugins
      - name: Install semantic-release and plugins
        run: |
          if [ ! -d "node_modules/@semantic-release" ]; then
            npm i -D semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/npm
          fi

      # Step 6: Run semantic-release
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
