name: Automate Release

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main

jobs:
  version_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      packages: write
      pull-requests: write

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 1.1: Configure Git
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 2: Configurate Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'npm'

      # Step 3: Configure .npmrc for GitHub Packages
      - name: Configure .npmrc for GitHub Packages
        run: |
          echo "@lordcrainer:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      # Step 4: Install semantic-release and plugins
      - name: Install ONLY release dependencies
        run: |
          npm install --no-package-lock --no-save \
            semantic-release@^23.x \
            @semantic-release/changelog@^6.x \
            @semantic-release/git@^10.x \
            @semantic-release/npm@^12.x

      # Step 5: Run semantic-release
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
